ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "pyXsurf"
  site-url: "https://vincenzooo.github.io/pyXsurf"
  description: "Python Library for X-Ray Optics, Metrology and Telescopes Design."
  twitter-card: true
  open-graph: true
  repo-branch: pyXsurf_nbdev
  repo-url: "https://github.com/vincenzooo/pyXsurf"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/vincenzooo/pyXsurf"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
