[tool.poetry]
name = "pyXsurf"
version = "1.5.2"
description = ""
authors = ["vincenzo"]
packages = [
{ include = "*", from = "source" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
